# Generated by Django 3.2.12 on 2023-02-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_auto_20230218_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='motorcycle_description',
            field=models.CharField(default='No description', max_length=500),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
