# Generated by Django 3.2.12 on 2023-02-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_auto_20230219_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='motorcycle_brand',
            field=models.CharField(default='No brand', max_length=20),
        ),
    ]
